# Generated by Django 3.1.2 on 2020-12-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configurazione',
            fields=[
                ('indice', models.IntegerField(primary_key=True, serialize=False)),
                ('durata', models.IntegerField()),
            ],
        ),
    ]
